//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     Generation parameters:
//     - DataFilename: Patterns\Italian\Italian-Numbers.yaml
//     - Language: Italian
//     - ClassName: NumbersDefinitions
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Recognizers.Definitions.Italian
{
	using System;
	using System.Collections.Generic;

	public static class NumbersDefinitions
	{
		public const string LangMarker = "it";
		public const string RoundNumberIntegerRegex = @"(cento|mille|milione|miliardo|trilione)";
		public const string ZeroToNineIntegerRegex = @"(tre|sette|otto|quattro|cinque|zero|nove|uno|due|sei)";
		public const string AnIntRegex = @"(un|uno|una)(?=\s)";
		public const string TenToNineteenIntegerRegex = @"(diciassette|tredici|quattordici|diciotto|diciannove|quindici|sedici|undici|dodici|dieci)";
		public const string TensNumberIntegerRegex = @"(settanta|venti|trenta|ottanta|novanta|quaranta|cinquanta|sessanta)";
		public static readonly string SeparaIntRegex = $@"((({TenToNineteenIntegerRegex}|({TensNumberIntegerRegex}(\s+(e\s+)?|\s*-\s*){ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex})(\s+{RoundNumberIntegerRegex})*))|(({AnIntRegex}(\s+{RoundNumberIntegerRegex})+))";
		public static readonly string AllIntRegex = $@"(((({TenToNineteenIntegerRegex}|({TensNumberIntegerRegex}(\s+(e\s+)?|\s*-\s*){ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex}|{AnIntRegex})(\s+{RoundNumberIntegerRegex})+)\s+(and\s+)?)*{SeparaIntRegex})";
		public const string PlaceHolderPureNumber = @"\b";
		public const string PlaceHolderDefault = @"\D|\b";
		public static readonly Func<string, string> NumbersWithPlaceHolder = (placeholder) => $@"(((?<!\d+\s*)-\s*)|(?<=\b))\d+(?!(\.\d+[a-zA-Z]))(?={placeholder})";
		public const string NumbersWithSuffix = @"(((?<!\d+\s*)-\s*)|(?<=\b))\d+\s*(K|k|M|T|G)(?=\b)";
		public static readonly string RoundNumberIntegerRegexWithLocks = $@"(?<=\b)\d+\s+{RoundNumberIntegerRegex}(?=\b)";
		public const string NumbersWithDozenSuffix = @"(((?<!\d+\s*)-\s*)|(?<=\b))\d+\s+dozzina(e)?(?=\b)";
		public static readonly string AllIntRegexWithLocks = $@"((?<=\b){AllIntRegex}(?=\b))";
		public static readonly string AllIntRegexWithDozenSuffixLocks = $@"(?<=\b)(((half\s+)?a\s+dozzina)|({AllIntRegex}\s+dozzina(e)?))(?=\b)";
		public const string RoundNumberOrdinalRegex = @"(centesimo(a)|millesimo(a)|milionesimo(a)|miliardesimo(a)|trilionesimo(a))";
		public const string BasicOrdinalRegex = @"(primo(a)|secondo(a)|terzo(a)|quarto(a)|quinto(a)|sesto(a)|settimo(a)|ottavo(a)|nono(a)|decimo(a)|undicesimo(a)|dodicesimo(a)|tredicesimo(a)|quattordicesimo(a)|quindicesimo(a)|sedicesimo(a)|diciassettesimo(a)|diciottesimo(a)|diciannovesimo(a)|ventesimo(a)|trentesimo(a)|quarantesimo(a)|cinquantesimo(a)|sessantesimo(a)|settantesimo(a)|otantesimo(a)|novantesimo(a))";
		public static readonly string SuffixBasicOrdinalRegex = $@"((((({TensNumberIntegerRegex}(\s+(e\s+)?|\s*-\s*){ZeroToNineIntegerRegex})|{TensNumberIntegerRegex}|{ZeroToNineIntegerRegex}|{AnIntRegex})(\s+{RoundNumberIntegerRegex})+)\s+(e\s+)?)*({TensNumberIntegerRegex}(\s+|\s*-\s*))?{BasicOrdinalRegex})";
		public static readonly string SuffixRoundNumberOrdinalRegex = $@"(({AllIntRegex}\s+){RoundNumberOrdinalRegex})";
		public static readonly string AllOrdinalRegex = $@"({SuffixBasicOrdinalRegex}|{SuffixRoundNumberOrdinalRegex})";
		public const string OrdinalSuffixRegex = @"(?<=\b)((\d*(1°|2°|3°|4°|5°|6°|7°|8°|9°|0°))|(11°|12°))(?=\b)";
		public const string OrdinalNumericRegex = @"(?<=\b)(\d{1,3}(\s*,\s*\d{3})*\s*°)(?=\b)";
		public static readonly string OrdinalRoundNumberRegex = $@"(?<!(un|uno|una)\s+){RoundNumberOrdinalRegex}";
		public static readonly string OrdinalEnglishRegex = $@"(?<=\b){AllOrdinalRegex}(?=\b)";
		public const string FractionNotationWithSpacesRegex = @"(((?<=\W|^)-\s*)|(?<=\b))\d+\s+\d+[/]\d+(?=(\b[^/]|$))";
		public const string FractionNotationRegex = @"(((?<=\W|^)-\s*)|(?<=\b))\d+[/]\d+(?=(\b[^/]|$))";
		public static readonly string FractionNounRegex = $@"(?<=\b)({AllIntRegex}\s+(e\s+)?)?({AllIntRegex})(\s+|\s*-\s*)((({AllOrdinalRegex})|({RoundNumberOrdinalRegex}))s|halves|quarters)(?=\b)";
		public static readonly string FractionNounWithArticleRegex = $@"(?<=\b)({AllIntRegex}\s+(e\s+)?)?(un|uno|una)(\s+|\s*-\s*)(({AllOrdinalRegex})|({RoundNumberOrdinalRegex})|mezzo|quarto)(?=\b)";
		public static readonly string FractionPrepositionRegex = $@"(?<=\b)(({AllIntRegex})|((?<!\.)\d+))\s+over\s+(({AllIntRegex})|(\d+)(?!\.))(?=\b)";
		public static readonly string AllPointRegex = $@"((\s+{ZeroToNineIntegerRegex})+|(\s+{SeparaIntRegex}))";
		public static readonly string AllFloatRegex = $@"{AllIntRegex}(\s+point){AllPointRegex}";
		public const string DoubleWithMultiplierRegex = @"(((?<!\d+\s*)-\s*)|((?<=\b)(?<!\d+\.)))\d+\.\d+\s*(K|k|M|G|T|B|b)(?=\b)";
		public const string DoubleExponentialNotationRegex = @"(((?<!\d+\s*)-\s*)|((?<=\b)(?<!\d+\.)))(\d+(\.\d+)?)e([+-]*[1-9]\d*)(?=\b)";
		public const string DoubleCaretExponentialNotationRegex = @"(((?<!\d+\s*)-\s*)|((?<=\b)(?<!\d+\.)))(\d+(\.\d+)?)\^([+-]*[1-9]\d*)(?=\b)";
		public static readonly Func<string, string> DoubleDecimalPointRegex = (placeholder) => $@"(((?<!\d+\s*)-\s*)|((?<=\b)(?<!\d+\.)))\d+\.\d+(?!(\.\d+))(?={placeholder})";
		public static readonly Func<string, string> DoubleWithoutIntegralRegex = (placeholder) => $@"(?<=\s|^)(?<!(\d+))\.\d+(?!(\.\d+))(?={placeholder})";
		public static readonly string DoubleWithRoundNumber = $@"(((?<!\d+\s*)-\s*)|((?<=\b)(?<!\d+\.)))\d+\.\d+\s+{RoundNumberIntegerRegex}(?=\b)";
		public static readonly string DoubleAllFloatRegex = $@"((?<=\b){AllFloatRegex}(?=\b))";
		public const string CurrencyRegex = @"(((?<=\W|^)-\s*)|(?<=\b))\d+\s*(B|b|m|t|g)(?=\b)";
		public static readonly string NumberWithSuffixPercentage = $@"({BaseNumbers.NumberReplaceToken})(\s*)(%|percento|per cento)";
		public static readonly string NumberWithPrefixPercentage = $@"(percento di|per cento di)(\s*)({BaseNumbers.NumberReplaceToken})";
		public const char DecimalSeparatorChar = ',';
		public const string FractionMarkerToken = "su";
		public const char NonDecimalSeparatorChar = '.';
		public const string HalfADozenText = "sei";
		public const string WordSeparatorToken = "e";
		public static readonly string[] WrittenDecimalSeparatorTexts = { "punto" };
		public static readonly string[] WrittenGroupSeparatorTexts = { "punto" };
		public static readonly string[] WrittenIntegerSeparatorTexts = { "e" };
		public static readonly string[] WrittenFractionSeparatorTexts = { "e" };
		public const string HalfADozenRegex = @"mezza\s+dozzina";
		public const string DigitalNumberRegex = @"((?<=\b)(cento|mille|milione|miliardo|trilione|dozzina(e)?)(?=\b))|((?<=(\d|\b))(k|t|m|g|b)(?=\b))";
		public static readonly Dictionary<string, long> CardinalNumberMap = new Dictionary<string, long>
		{
			{ "a", 1 },
			{ "zero", 0 },
			{ "an", 1 },
			{ "one", 1 },
			{ "two", 2 },
			{ "three", 3 },
			{ "four", 4 },
			{ "five", 5 },
			{ "six", 6 },
			{ "seven", 7 },
			{ "eight", 8 },
			{ "nine", 9 },
			{ "ten", 10 },
			{ "eleven", 11 },
			{ "twelve", 12 },
			{ "dozen", 12 },
			{ "dozens", 12 },
			{ "thirteen", 13 },
			{ "fourteen", 14 },
			{ "fifteen", 15 },
			{ "sixteen", 16 },
			{ "seventeen", 17 },
			{ "eighteen", 18 },
			{ "nineteen", 19 },
			{ "twenty", 20 },
			{ "thirty", 30 },
			{ "forty", 40 },
			{ "fifty", 50 },
			{ "sixty", 60 },
			{ "seventy", 70 },
			{ "eighty", 80 },
			{ "ninety", 90 },
			{ "hundred", 100 },
			{ "thousand", 1000 },
			{ "million", 1000000 },
			{ "billion", 1000000000 },
			{ "trillion", 1000000000000 }
		};
		public static readonly Dictionary<string, long> OrdinalNumberMap = new Dictionary<string, long>
		{
			{ "first", 1 },
			{ "second", 2 },
			{ "secondary", 2 },
			{ "half", 2 },
			{ "third", 3 },
			{ "fourth", 4 },
			{ "quarter", 4 },
			{ "fifth", 5 },
			{ "sixth", 6 },
			{ "seventh", 7 },
			{ "eighth", 8 },
			{ "ninth", 9 },
			{ "tenth", 10 },
			{ "eleventh", 11 },
			{ "twelfth", 12 },
			{ "thirteenth", 13 },
			{ "fourteenth", 14 },
			{ "fifteenth", 15 },
			{ "sixteenth", 16 },
			{ "seventeenth", 17 },
			{ "eighteenth", 18 },
			{ "nineteenth", 19 },
			{ "twentieth", 20 },
			{ "thirtieth", 30 },
			{ "fortieth", 40 },
			{ "fiftieth", 50 },
			{ "sixtieth", 60 },
			{ "seventieth", 70 },
			{ "eightieth", 80 },
			{ "ninetieth", 90 },
			{ "hundredth", 100 },
			{ "thousandth", 1000 },
			{ "millionth", 1000000 },
			{ "billionth", 1000000000 },
			{ "trillionth", 1000000000000 },
			{ "firsts", 1 },
			{ "halves", 2 },
			{ "thirds", 3 },
			{ "fourths", 4 },
			{ "quarters", 4 },
			{ "fifths", 5 },
			{ "sixths", 6 },
			{ "sevenths", 7 },
			{ "eighths", 8 },
			{ "ninths", 9 },
			{ "tenths", 10 },
			{ "elevenths", 11 },
			{ "twelfths", 12 },
			{ "thirteenths", 13 },
			{ "fourteenths", 14 },
			{ "fifteenths", 15 },
			{ "sixteenths", 16 },
			{ "seventeenths", 17 },
			{ "eighteenths", 18 },
			{ "nineteenths", 19 },
			{ "twentieths", 20 },
			{ "thirtieths", 30 },
			{ "fortieths", 40 },
			{ "fiftieths", 50 },
			{ "sixtieths", 60 },
			{ "seventieths", 70 },
			{ "eightieths", 80 },
			{ "ninetieths", 90 },
			{ "hundredths", 100 },
			{ "thousandths", 1000 },
			{ "millionths", 1000000 },
			{ "billionths", 1000000000 },
			{ "trillionths", 1000000000000 }
		};
		public static readonly Dictionary<string, long> RoundNumberMap = new Dictionary<string, long>
		{
			{ "hundred", 100 },
			{ "thousand", 1000 },
			{ "million", 1000000 },
			{ "billion", 1000000000 },
			{ "trillion", 1000000000000 },
			{ "hundredth", 100 },
			{ "thousandth", 1000 },
			{ "millionth", 1000000 },
			{ "billionth", 1000000000 },
			{ "trillionth", 1000000000000 },
			{ "hundredths", 100 },
			{ "thousandths", 1000 },
			{ "millionths", 1000000 },
			{ "billionths", 1000000000 },
			{ "trillionths", 1000000000000 },
			{ "dozen", 12 },
			{ "dozens", 12 },
			{ "k", 1000 },
			{ "m", 1000000 },
			{ "g", 1000000000 },
			{ "b", 1000000000 },
			{ "t", 1000000000000 }
		};
	}
}